### PR TITLE
Migrate to NPM and Typescript

### PR DESCRIPTION
**Pull request by rodydavis**
- Remove Bower and use NPM
- Update README
- Migrate JS code to TS
- Add legacy dependencies in `third_party`
- Rename `app/js/` to `app/ts/`
- Adding types where available
- Added `package.json` and `tsconfig.json`

### CODE REVIEW

**Comment by rodydavis** [comment]
@jverkoey

**Comment by appsforartists** [comment]
Really surprised to see action on this repo.  Thanks for the effort!

A few notes from a quick look I took:  (This diff is so big that GitHub's review UI is choking)

- [ ] `rodydavis/direct` should be `material-motion/direct` in `package.json`
- [ ] I see npm packages for [angular-ui-sortable](https://www.npmjs.com/package/angular-ui-sortable) and [jquery-ui](https://www.npmjs.com/package/jquery-ui). Can we use those instead, and totally remove `bower` + `third_party`?
- [ ] The canonical script name to start a server is [`start`](https://docs.npmjs.com/cli/v7/using-npm/scripts#npm-start).  Can we please use that instead?
- [ ] It's a real bummer that starting the server asks for your sudo password with no context.  I haven't used AppEngine since the `dev_appserver` days, but I know they use `gcloud` now.  I wonder if there's a command that doesn't require `sudo`,  and doesn't require another massive refactor.

    Makes me wonder if we should port this to Firebase {Hosting, Firestore} (in a separate PR).
- [ ] I believe Google Style is to use single quotes instead of double.  (It's a total nit, but that's why I now use singles.)  I wonder if https://github.com/google/gts would be helpful for this project.
- [ ] It would also be nice if the server watched the filesystem and rebuilt when changes were made, but that may be out-of-scope for this PR.

**Comment by rodydavis** [comment]
> * [ ]  `rodydavis/direct` should be `material-motion/direct` in `package.json`
Updated!
> * [ ]  I see npm packages for [angular-ui-sortable](https://www.npmjs.com/package/angular-ui-sortable) and [jquery-ui](https://www.npmjs.com/package/jquery-ui). Can we use those instead, and totally remove `bower` + `third_party`?
The ones on npm were not compiling and were not supporting the other packages. Basically it couldn't resolve the dependencies. This will be remove when I remove jquery and update angular.
> * [ ]  The canonical script name to start a server is [`start`](https://docs.npmjs.com/cli/v7/using-npm/scripts#npm-start).  Can we please use that instead?Updated!
> * [ ]  It's a real bummer that starting the server asks for your sudo password with no context.  I haven't used AppEngine since the `dev_appserver` days, but I know they use `gcloud` now.  I wonder if there's a command that doesn't require `sudo`,  and doesn't require another massive refactor.
I was trying to get the sdk to use the gcloud but not working at the moment. Maybe if we switch it to cloud run.
>   Makes me wonder if we should port this to Firebase {Hosting, Firestore} (in a separate PR).
I think that would be good. I am working to migrate it to the latest angular but right now it requires app engine.
> * [ ]  I believe Google Style is to use single quotes instead of double.  (It's a total nit, but that's why I now use singles.)  I wonder if https://github.com/google/gts would be helpful for this project.
Installed the style guide but the tsconfig it extends is not outputting the correct ts, so I made the change to single quotes.
> * [ ]  It would also be nice if the server watched the filesystem and rebuilt when changes were made, but that may be out-of-scope for this PR.
I added a watch command for ts and it is working. On terminal you run `npm run ts:watch` and the other `npm run start`.

**Comment by rodydavis** [comment]
@appsforartists can you take another look?

**Comment by rodydavis** [comment]
@jverkoey also if you could review

**Comment by appsforartists** [comment]
Looks like most of the changes I recommended are in there.  It's a bummer that you can't run `ts:watch` and `sudo dev_appserver` in the same command.

I think `start` should tell you why you're being asked for your password:

```
    "start": "npm run ts; echo \"sudo starting Google AppEngine\"; sudo dev_appserver.py .",
```

Also, the README needs to be updated with your changes; namely, `start` instead of `serve` and a note about running `ts:watch` and `start` in separate terminal sessions.

I don't have enough familiarity with Angular or Direct to give a more thorough review, but otherwise, LGTM.  Thanks again!

**Comment by rodydavis** [comment]
Updated messaging!

**Comment by appsforartists** [comment]
Does `bower install` not need to be run anymore?  I see the script is missing, but it's still listed in `devDependencies`

**Comment by rodydavis** [comment]
Thats correct!

**Comment by rodydavis** [comment]
@jverkoey

**Review by jverkoey — APPROVED** [review]
Gonna apply a trust and verify lens here; once this merges let's make sure it deploys internally and then adjust anything in follow-ups as needed :)

**Pull request merged**
